version: '3'

services:
    server:
        build: ./server
        image: goal/server
        env_file: ./server/.env
        ports:
            - "3001:3001"
        command: npm run docker
        volumes: 
            - ./server:/app
            - /app/node_modules

    client:
        build: ./client
        image: goal/client
        ports:
            - "3000:3000"
        command: npm start
        volumes: 
            - ./client:/app
            - /app/node_modules
 

    mongodb:
        image: mongo:4.0.20-xenial
        volumes: 
            - mongodbdata:/data/db
    
volumes:
    mongodbdata:
